export { default as MenuIcon } from '@mui/icons-material/Menu';
export { default as RoomIcon } from '@mui/icons-material/Room';
export { default as SearchIcon } from '@mui/icons-material/Search';
export { default as EmojiPeopleIcon } from '@mui/icons-material/EmojiPeople';
export { default as BlockIcon } from '@mui/icons-material/Block';
export { default as CheckCircleOutlineIcon } from '@mui/icons-material/CheckCircleOutline';
export { default as GroupsIcon } from '@mui/icons-material/Groups';
export { default as ContactPageIcon } from '@mui/icons-material/ContactPage';
export { default as CheckIcon } from '@mui/icons-material/Check';
